# Generated by Django 3.1.3 on 2020-11-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieptt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(blank=True, max_length=255, verbose_name='Release_date'),
        ),
    ]
