# Generated by Django 3.1.3 on 2020-11-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieptt', '0002_auto_20201110_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='last_modified',
            field=models.CharField(blank=True, max_length=255, verbose_name='Last_modified'),
        ),
    ]
