# Generated by Django 3.1.3 on 2020-11-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieptt', '0003_auto_20201110_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last_modified'),
        ),
    ]
