# Generated by Django 3.2 on 2020-10-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('critics_consensus', models.TextField(blank=True, null=True, verbose_name='Consensus')),
                ('date', models.CharField(blank=True, max_length=255, null=True, verbose_name='date')),
                ('duration', models.CharField(blank=True, max_length=255, null=True, verbose_name='duration')),
                ('genre', models.CharField(blank=True, max_length=255, null=True, verbose_name='genre')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='rating')),
                ('images', models.ImageField(blank=True, null=True, upload_to='movie/images/', verbose_name='images')),
                ('amount_reviews', models.CharField(blank=True, max_length=255, null=True, verbose_name='amount_reviews')),
                ('approval_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Porcentae')),
            ],
        ),
        migrations.CreateModel(
            name='PttMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author')),
                ('contenttext', models.TextField(blank=True, null=True, verbose_name='Contenttext')),
                ('date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Date')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('key_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieptt.movie')),
            ],
        ),
    ]
