# Generated by Django 2.1.1 on 2020-11-06 07:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountGoodAndBad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_ray', models.IntegerField(default=0, verbose_name='Good_ray')),
                ('bad_ray', models.IntegerField(default=0, verbose_name='Bad_ray')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('critics_consensus', models.TextField(blank=True, verbose_name='Consensus')),
                ('release_date', models.DateField(default=datetime.date.today, verbose_name='Release_date')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last_modified')),
                ('duration', models.CharField(blank=True, max_length=255, verbose_name='Duration')),
                ('genre', models.CharField(blank=True, max_length=255, verbose_name='Genre')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Rating')),
                ('images', models.ImageField(blank=True, upload_to='', verbose_name='Images')),
                ('amount_reviews', models.CharField(blank=True, max_length=255, verbose_name='Amount_reviews')),
                ('approval_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Porcentae')),
            ],
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='yahoo/')),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movieptt.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='PttMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Author')),
                ('contenttext', models.TextField(blank=True, verbose_name='Contenttext')),
                ('date', models.CharField(blank=True, max_length=255, verbose_name='Date')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('key_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movieptt.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='countgoodandbad',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movieptt.Movie'),
        ),
    ]
