# Generated by Django 3.2 on 2020-10-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieptt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pttmovie',
            name='key_word',
        ),
    ]
