# Generated by Django 3.2 on 2020-10-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieptt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='approval_percentage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Porcentae'),
        ),
    ]
