# Generated by Django 3.2 on 2020-10-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieptt', '0002_remove_pttmovie_key_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='pttmovie',
            name='key_word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movieptt.movie'),
            preserve_default=False,
        ),
    ]
