# Generated by Django 3.2 on 2020-10-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieptt', '0003_auto_20201016_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='movieimage',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movieptt.movie'),
        ),
        migrations.AlterField(
            model_name='pttmovie',
            name='key_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movieptt.movie'),
        ),
        migrations.CreateModel(
            name='CountGoodAndBad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_ray', models.CharField(blank=True, max_length=255, verbose_name='Good_ray')),
                ('bad_ray', models.CharField(blank=True, max_length=255, verbose_name='Bad_ray')),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movieptt.movie')),
            ],
        ),
    ]
