# Generated by Django 3.1 on 2020-10-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieptt', '0004_auto_20201004_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pttmovie',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
