# Generated by Django 3.2 on 2020-10-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieptt', '0004_auto_20201019_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countgoodandbad',
            name='bad_ray',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bad_ray'),
        ),
        migrations.AlterField(
            model_name='countgoodandbad',
            name='good_ray',
            field=models.IntegerField(blank=True, null=True, verbose_name='Good_ray'),
        ),
    ]
