# Generated by Django 3.1 on 2020-10-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieptt', '0005_auto_20201004_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pttmovie',
            name='key_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movieptt.movie'),
        ),
    ]
