# Generated by Django 3.2 on 2020-10-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieptt', '0006_auto_20201019_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countgoodandbad',
            name='bad_ray',
            field=models.IntegerField(default=0, verbose_name='Bad_ray'),
        ),
        migrations.AlterField(
            model_name='countgoodandbad',
            name='good_ray',
            field=models.IntegerField(default=0, verbose_name='Good_ray'),
        ),
    ]
